id: a96353db3c16457098af5595c6db1b72
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_252-The_Fourfold_Accomplishment-v2
  language: en
  author: ''
  volume: {}
